var constants = require("node-constants")(exports);
constants({
    MEDIA_TYPE_PDF: 'pdf',
    MEDIA_TYPE_VIDEO: 'video',
    Y : 'Y',
    N : 'N',
    DATA_NOT_AVAILABLE : 'DataNotAvailable',
    NO_DATA_STATUS_CODE : 2002,
    OK_STATUS_CODE : 2001,
    ERROR_STATUS_CODE : 5001,
    SUCCESS : "Success",
    SEVERE : "Severe",
    DEBUG : "Debug",
    FAILED : 'Failed',
    NO_IMAGE : 'not_available.jpg',
    SELF_PACED : 'Self-Paced',
    ONLINE : 'Online',
    COMPLETED : 'Completed',
    COACHING_CLASSES : 'Coaching Classes',
    ENTRANCE_EXAMS : 'Entrance Exams',
    CODE_CLUB : 'Code Club',
    ADA : 'Ada',
    LANGUAGES : 'Languages',
});
